apiVersion: apps/v1beta7
kind: Deployment
metadata:
  name: celery-worker
  namespace: gridscale
  labels:
    deployment: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: celery-worker
  template:
    metadata:
      labels:
        pod: celery-worker
    spec:
      containers:
        - name: celery-worker
          image: gitumarkk/k8_django_minikube:part_4
          command: ['celery', '-A', 'kubernetes_django', 'worker', '-l', 'info']
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: user

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password

            - name: POSTGRES_HOST
              value: postgres-service

            - name: REDIS_HOST
              value: redis-service
