kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  namespace: gridscale
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgres-pv

